approval_policy = "untrusted"
hide_agent_reasoning = true
model = "gpt-5-codex"
model_reasoning_effort = "high"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[projects."/home/kubosho/src/github.com/kubosho/blog.kubosho.com"]
trust_level = "trusted"

[projects."/home/kubosho/src/github.com/kubosho/articles"]
trust_level = "trusted"

[tools]
web_search = true
