approval_policy = "untrusted"
model = "gpt-5-codex"
sandbox_mode = "workspace-write"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[projects."/home/kubosho/src/github.com/kubosho/articles"]
trust_level = "trusted"

[projects."/home/kubosho/src/github.com/kubosho/blog.kubosho.com"]
trust_level = "trusted"

[projects."/home/kubosho/src/github.com/kubosho/sensei-mode"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true

[tools]
web_search = true
